package com.npdev.generator.migration;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

public final class MigrationScriptEmitter {

    public Path emit(Path outputDir, String fileName, MigrationPlan plan) throws Exception {
        if (outputDir == null) {
            throw new IllegalArgumentException("outputDir must be non-null");
        }
        if (fileName == null || fileName.isBlank()) {
            throw new IllegalArgumentException("fileName must be non-blank");
        }
        Files.createDirectories(outputDir);

        MigrationPlan normalized = plan == null ? new MigrationPlan(java.util.List.of()) : plan.normalized();
        StringBuilder sql = new StringBuilder();
        sql.append("-- NPDev deterministic migration plan\n");
        sql.append("-- Generated by MigrationScriptEmitter\n\n");

        for (MigrationOperation op : normalized.operations()) {
            switch (op.kind()) {
                case CREATE_TABLE -> {
                    sql.append("CREATE TABLE IF NOT EXISTS ")
                            .append(op.tableName())
                            .append(" (id UUID PRIMARY KEY);\n");
                }
                case ADD_COLUMN -> {
                    sql.append("ALTER TABLE ")
                            .append(op.tableName())
                            .append(" ADD COLUMN IF NOT EXISTS ")
                            .append(op.columnName())
                            .append(" ")
                            .append(renderSqlType(op.sqlType()))
                            .append(";\n");
                }
                case SET_NOT_NULL -> {
                    sql.append("ALTER TABLE ")
                            .append(op.tableName())
                            .append(" ALTER COLUMN ")
                            .append(op.columnName())
                            .append(" SET NOT NULL;\n");
                }
                case CREATE_UNIQUE_INDEX -> {
                    String indexName = "ux_" + op.tableName() + "_" + op.columnName();
                    if (indexName.length() > 60) {
                        indexName = indexName.substring(0, 60);
                    }
                    sql.append("CREATE UNIQUE INDEX IF NOT EXISTS ")
                            .append(indexName)
                            .append(" ON ")
                            .append(op.tableName())
                            .append(" (")
                            .append(op.columnName())
                            .append(");\n");
                }
            }
        }

        Path file = outputDir.resolve(fileName);
        Files.writeString(file, sql.toString(), StandardCharsets.UTF_8);
        return file;
    }

    private static String renderSqlType(String sqlType) {
        if (sqlType == null || sqlType.isBlank()) {
            return "VARCHAR(255)";
        }
        String normalized = sqlType.trim();
        if ("VARCHAR".equalsIgnoreCase(normalized)) {
            return "VARCHAR(255)";
        }
        return normalized;
    }
}
