package com.finalexec.db;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.npdev.dsl.v1.compiled.CompiledConcept;
import com.npdev.dsl.v1.compiled.CompiledField;
import com.npdev.dsl.v1.compiled.CompiledModel;
import com.npdev.generator.dbconfig.DatabaseEngine;
import com.npdev.generator.dbconfig.GeneratedDatabasePlan;
import com.npdev.generator.dbconfig.SchemaLifecyclePolicy;
import com.npdev.generator.dbconfig.SchemaLifecycleStrategy;
import com.npdev.generator.dbconfig.SchemaRealizationEmitter;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import javax.sql.DataSource;
import java.io.PrintWriter;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.logging.Logger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * REG-40 tactical hotfix (schema-engine rebuild plan, Part II, step R.3): end-to-end proof that a
 * brand-new concept added to the model gets a REAL table on an upgrade boot against an
 * already-existing database. Unlike {@link SchemaLifecycleExecutorAdditiveChangeTest} (which drives
 * only the classification method {@code isSafeAdditiveChange} against a hand-crafted manifest),
 * this test drives the actual production boot entry point ({@link
 * SchemaLifecycleExecutor#migrate(Flyway, SchemaLifecycleExecutor.SchemaManifest)}) against REAL
 * Flyway migrations generated by {@link SchemaRealizationEmitter} for two successive model
 * versions: boot with model v1 (one concept, Order) -&gt; insert a row -&gt; "upgrade" to model v2
 * (adds Customer) -&gt; boot again -&gt; assert the new table exists, the old row survived, and
 * history recorded a normal APPLIED outcome (not a refusal or a "Table not found" crash).
 *
 * <p>Before the R.2 emitter fix, {@code R__npdev_schema_additive_columns.sql} emitted only {@code
 * ALTER TABLE ... ADD COLUMN} statements. Since Flyway's versioned {@code V1__} migration never
 * re-runs once applied, a brand-new concept's table was never created on an upgrade boot -- the
 * app crashed at runtime the first time generated JPA/JDBC code touched the missing table, even
 * though {@code classify()} itself (see the "Table doesn't exist yet" branch, ~line 2115) already
 * treated the new table as non-blocking and let the boot proceed.
 */
class SchemaLifecycleExecutorNewTableOnExistingDbTest {

    @TempDir
    Path tempDir;

    private final SchemaLifecycleExecutor executor = new SchemaLifecycleExecutor();
    private DataSource dataSource;

    @BeforeEach
    void setUp() {
        String url = "jdbc:h2:mem:" + getClass().getSimpleName() + System.nanoTime() + ";DB_CLOSE_DELAY=-1";
        dataSource = new SingleConnectionUrlDataSource(url);
    }

    @AfterEach
    void tearDown() throws SQLException {
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("DROP ALL OBJECTS");
        }
    }

    @Test
    void newConceptAddedOnUpgradeGetsItsTableWithoutLosingExistingData() throws Exception {
        CompiledConcept order = new CompiledConcept("Order", "Order", "orders", List.of(
                new CompiledField("id", "uuid", "java.util.UUID", true, true, false),
                new CompiledField("name", "string", "String", false, true, false)
        ));
        CompiledModel modelV1 = new CompiledModel("test", "1.0.0", "1.0.0", Map.of(order.getName(), order));

        Path appV1 = tempDir.resolve("app-v1");
        new SchemaRealizationEmitter().emit(modelV1, appV1, plan("v1"), tempDir.resolve("model-v1.json"));
        SchemaLifecycleExecutor.SchemaManifest manifestV1 = manifestFrom(appV1, "sha256:v1");

        // Boot 1: genuinely fresh database -- V1 creates 'orders', R__ additive is a no-op.
        executor.migrate(flywayFor(appV1), manifestV1);

        String orderId = UUID.randomUUID().toString();
        try (Connection connection = dataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement(
                     "INSERT INTO orders (id, name, version, row_version, tenant_id) VALUES (?, ?, 0, 0, 'default')")) {
            statement.setString(1, orderId);
            statement.setString(2, "first order");
            statement.executeUpdate();
        }

        // Model v2: the same Order concept, PLUS a brand-new Customer concept -- the REG-40 scenario.
        CompiledConcept customer = new CompiledConcept("Customer", "Customer", "customers", List.of(
                new CompiledField("id", "uuid", "java.util.UUID", true, true, false),
                new CompiledField("name", "string", "String", false, true, false)
        ));
        CompiledModel modelV2 = new CompiledModel("test", "1.0.0", "1.0.0",
                Map.of(order.getName(), order, customer.getName(), customer));

        Path appV2 = tempDir.resolve("app-v2");
        new SchemaRealizationEmitter().emit(modelV2, appV2, plan("v2"), tempDir.resolve("model-v2.json"));
        SchemaLifecycleExecutor.SchemaManifest manifestV2 = manifestFrom(appV2, "sha256:v2");

        // Boot 2: "upgrade" against the SAME database. V1 (versioned) never re-runs; only R__
        // (repeatable) does. Before the REG-40 hotfix, 'customers' was never created here.
        executor.migrate(flywayFor(appV2), manifestV2);

        try (Connection connection = dataSource.getConnection()) {
            try (Statement statement = connection.createStatement();
                 ResultSet rs = statement.executeQuery("SELECT COUNT(*) FROM customers")) {
                assertTrue(rs.next());
                assertEquals(0, rs.getInt(1), "brand-new 'customers' table must exist (empty) after the upgrade boot");
            }
            try (Statement statement = connection.createStatement();
                 ResultSet rs = statement.executeQuery("SELECT id, name FROM orders")) {
                assertTrue(rs.next(), "the pre-existing 'orders' row must survive the upgrade");
                assertEquals(orderId, rs.getString("id"));
                assertEquals("first order", rs.getString("name"));
                assertFalse(rs.next(), "no extra rows should have appeared in 'orders'");
            }
            try (Statement statement = connection.createStatement();
                 ResultSet rs = statement.executeQuery(
                         "SELECT outcome FROM npdev_schema_history WHERE to_fingerprint = 'sha256:v2'")) {
                assertTrue(rs.next(), "the upgrade boot must have recorded a history row for the new fingerprint");
                assertEquals("APPLIED", rs.getString("outcome"),
                        "a brand-new table is a safe-additive change and must apply cleanly, not refuse");
            }
        }
    }

    private Flyway flywayFor(Path appRoot) {
        Path schemaDir = appRoot.resolve("src/main/resources/db/schema-realization");
        return Flyway.configure()
                .dataSource(dataSource)
                .locations("filesystem:" + schemaDir.toAbsolutePath())
                .load();
    }

    private GeneratedDatabasePlan plan(String suffix) {
        String appId = "reg40-" + suffix;
        return new GeneratedDatabasePlan(
                appId,
                DatabaseEngine.H2_LOCAL,
                DatabaseEngine.H2_LOCAL.storageMode(),
                true,
                appId,
                appId,
                "test",
                tempDir.resolve("data-" + suffix).toString(),
                "db-instance",
                "",
                "",
                0,
                0,
                "jdbc:h2:mem:" + appId,
                "org.h2.Driver",
                "sa",
                "",
                "",
                0,
                "",
                "",
                false,
                true,
                new SchemaLifecyclePolicy(
                        SchemaLifecycleStrategy.KEEP_EXISTING_IF_COMPATIBLE,
                        false,
                        "",
                        SchemaLifecyclePolicy.NPDEV_TABLE_SCOPE
                ),
                "unused-generation-time-fingerprint-" + suffix,
                tempDir.resolve("database-" + suffix + ".json"),
                List.of("test")
        );
    }

    /**
     * Reads only the two column-set fields the executor actually needs to classify this scenario
     * out of the REAL manifest {@link SchemaRealizationEmitter#emit} just wrote, so the test proves
     * the fix against genuine generator output rather than a hand-typed column list. The boot
     * fingerprint is passed in directly (independent of generation-time content) since {@link
     * SchemaLifecycleExecutor#migrate} only compares it for equality against the previously stored
     * value, never parses it.
     */
    private static SchemaLifecycleExecutor.SchemaManifest manifestFrom(Path appRoot, String fingerprint) throws Exception {
        JsonNode manifest = new ObjectMapper().readTree(
                appRoot.resolve("src/main/resources/npdev/db/schema-realization-manifest.json").toFile());
        Map<String, List<String>> businessTableColumns = toStringListMap(manifest.path("businessTableColumns"));
        Map<String, List<String>> businessTableAdditiveColumns = toStringListMap(manifest.path("businessTableAdditiveColumns"));
        // Carried over (rather than left empty) so beforeMigrate's unconditional relax pass doesn't
        // mistake every declared-required column for "no longer required" and loosen it -- a real,
        // but unrelated-to-REG-40, side effect that would otherwise muddy this scenario's assertions.
        Map<String, List<String>> businessTableRequiredColumns = toStringListMap(manifest.path("businessTableRequiredColumns"));
        return new SchemaLifecycleExecutor.SchemaManifest(
                "H2Local",
                "jdbc",
                true,
                fingerprint,
                List.of(),
                List.copyOf(businessTableColumns.keySet()),
                businessTableColumns,
                businessTableAdditiveColumns,
                Map.of(),
                Map.of(),
                Map.of(),
                false,
                "KeepExistingIfCompatible",
                SchemaLifecyclePolicy.NPDEV_TABLE_SCOPE,
                "",
                "",
                businessTableRequiredColumns,
                Map.of(),
                Map.of(),
                Map.of()
        );
    }

    private static Map<String, List<String>> toStringListMap(JsonNode object) {
        Map<String, List<String>> out = new LinkedHashMap<>();
        object.fields().forEachRemaining(entry -> {
            List<String> values = new ArrayList<>();
            entry.getValue().forEach(item -> values.add(item.asText()));
            out.put(entry.getKey(), values);
        });
        return out;
    }

    /** Minimal {@link DataSource} wrapping {@link DriverManager}; avoids pulling in an H2-specific compile-time dependency. */
    private static final class SingleConnectionUrlDataSource implements DataSource {
        private final String url;

        private SingleConnectionUrlDataSource(String url) {
            this.url = url;
        }

        @Override
        public Connection getConnection() throws SQLException {
            return DriverManager.getConnection(url);
        }

        @Override
        public Connection getConnection(String username, String password) throws SQLException {
            return DriverManager.getConnection(url, username, password);
        }

        @Override
        public PrintWriter getLogWriter() {
            return null;
        }

        @Override
        public void setLogWriter(PrintWriter out) {
        }

        @Override
        public void setLoginTimeout(int seconds) {
        }

        @Override
        public int getLoginTimeout() {
            return 0;
        }

        @Override
        public Logger getParentLogger() {
            return Logger.getLogger(getClass().getName());
        }

        @Override
        public <T> T unwrap(Class<T> iface) throws SQLException {
            throw new SQLException("not a wrapper");
        }

        @Override
        public boolean isWrapperFor(Class<?> iface) {
            return false;
        }
    }
}
