package com.finalexec.db.datamobility;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.core.io.ClassPathResource;

import java.io.IOException;
import java.io.InputStream;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * Resolves a data-mobility {@code --tables all|business|<comma-list>} selection against the
 * classpath {@code npdev/metadata/concepts.manifest.json} -- the same manifest
 * {@code TenantExportService} reads, generated by {@code CompiledMetadataCanonicalJson}. Runs
 * against whichever app's classpath the caller (a standalone {@code main}, no Spring context
 * needed) was launched with, exactly like {@code SchemaManifestLoader}.
 *
 * <p>"Business" means a concept declared directly in the app's own model root -- no pack origin
 * at all. A concept contributed by ANY pack, including the platform's own identity/workspace
 * built-ins, is never business (see {@code CompiledMetadataCanonicalJson}'s {@code packId}/
 * {@code isBusiness} fields, added alongside this class).
 */
public final class TableScopeResolver {

    private static final String MANIFEST_PATH = "npdev/metadata/concepts.manifest.json";

    private final ObjectMapper objectMapper;

    public TableScopeResolver() {
        this(new ObjectMapper());
    }

    TableScopeResolver(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    public enum Scope { ALL, BUSINESS, EXPLICIT }

    /**
     * @param scope        which selection rule to apply
     * @param explicitTables lower-cased table names to keep when {@code scope == EXPLICIT};
     *                     ignored otherwise
     * @return lower-cased table names in scope, or empty if the manifest can't be read (a caller
     *         should treat that as "nothing resolvable", never as "everything"
     */
    public Set<String> resolve(Scope scope, Set<String> explicitTables) {
        List<JsonNode> concepts = loadConcepts();
        Set<String> tables = new LinkedHashSet<>();
        Set<String> lowerExplicit = new LinkedHashSet<>();
        if (explicitTables != null) {
            for (String t : explicitTables) {
                lowerExplicit.add(t.trim().toLowerCase(Locale.ROOT));
            }
        }
        for (JsonNode concept : concepts) {
            String tableName = concept.path("tableName").asText("");
            if (tableName.isBlank()) {
                continue;
            }
            boolean isBusiness = concept.path("isBusiness").asBoolean(false);
            switch (scope) {
                case ALL -> tables.add(tableName.toLowerCase(Locale.ROOT));
                case BUSINESS -> {
                    if (isBusiness) {
                        tables.add(tableName.toLowerCase(Locale.ROOT));
                    }
                }
                case EXPLICIT -> {
                    String lower = tableName.toLowerCase(Locale.ROOT);
                    if (lowerExplicit.contains(lower)) {
                        tables.add(lower);
                    }
                }
            }
        }
        return Set.copyOf(tables);
    }

    private List<JsonNode> loadConcepts() {
        try {
            ClassPathResource resource = new ClassPathResource(MANIFEST_PATH);
            if (!resource.exists()) {
                return List.of();
            }
            try (InputStream in = resource.getInputStream()) {
                JsonNode manifest = objectMapper.readTree(in);
                JsonNode items = manifest.path("items");
                return items.isArray() ? toNodeList(items) : List.of();
            }
        } catch (IOException exception) {
            throw new IllegalStateException("Failed to read concepts manifest: " + exception.getMessage(), exception);
        }
    }

    private static List<JsonNode> toNodeList(JsonNode arrayNode) {
        List<JsonNode> out = new java.util.ArrayList<>();
        arrayNode.forEach(out::add);
        return out;
    }
}
