# Warning deployment profile.
npdev.runtime.deployment-profile=warning
npdev.runtime.deployment.bindings-manifest=npdev/bindings/alt.bindings.json
npdev.runtime.deployment.plugin-manifest=npdev/plugins/warning.plugin-manifest.json
npdev.runtime.execution-environment=warning
