package com.npdev.kernel.storage.sql;

import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.Set;

/**
 * H2, in the PostgreSQL compatibility mode every NPDev {@code H2Local}/{@code H2Server} app runs in.
 *
 * <p><b>This dialect is not new behaviour.</b> S1 forbids adding a second engine, and this does not
 * add one: two production sites already branched on
 * {@code connection.getMetaData().getDatabaseProductName().contains("h2")} and emitted a different
 * upsert -- {@code PostgresPersistenceCapabilityAdapter.buildH2UpsertSql} and
 * {@code JdbcBusinessConceptStore.upsertSql}. There were already two dialects in the codebase,
 * discovered per-connection and spelled twice. Extracting them here is the behaviour-preserving move;
 * leaving them inline would have been the behaviour-changing one, because routing everything through
 * {@link PostgresDialect} would have handed H2 an {@code ON CONFLICT} it does not accept.
 *
 * <p><b>Boundary B11: H2 does not roll DDL back.</b> {@link StorageCapability#DDL_IN_TRANSACTION} is
 * therefore absent from {@link #capabilities()} -- an existing, already-recorded limitation now
 * stated where the schema engine can consult it instead of assuming.
 */
public final class H2Dialect implements SqlDialect {

    public static final H2Dialect INSTANCE = new H2Dialect();

    static final String LIMIT_OFFSET_CLAUSE = "LIMIT ? OFFSET ?";
    static final String LIMIT_ONLY_CLAUSE = "LIMIT ?";
    static final String ROW_LIMIT_PREFIX = "LIMIT ";

    /**
     * Both spellings, deliberately. H2 reports a JSON column's type name inconsistently, and data
     * promoted from a Postgres source carries {@code jsonb} in its manifest -- the two sites that ask
     * this question ({@code JdbcBusinessConceptStore}, {@code SchemaDropSnapshotWriter}) accepted both
     * before extraction, and narrowing that here would make an H2 app start handing JSON-encoded
     * strings through unparsed.
     */
    private static final Set<String> JSON_TYPE_NAMES = Set.of("json", "jsonb");

    /** H2 exposes INFORMATION_SCHEMA; it has no pg_catalog, but the Postgres-compat layer answers for it. */
    private static final Set<String> SYSTEM_SCHEMAS = Set.of("information_schema", "pg_catalog");

    private static final Set<StorageCapability> CAPABILITIES = Set.of(
            StorageCapability.TRANSACTIONS,
            // DDL_IN_TRANSACTION deliberately absent -- boundary B11.
            StorageCapability.SCHEMA_EVOLUTION,
            StorageCapability.FOREIGN_KEYS,
            StorageCapability.UNIQUE_CONSTRAINTS,
            StorageCapability.SERVER_SIDE_JOIN,
            StorageCapability.AGGREGATION_PIPELINE,
            StorageCapability.OPTIMISTIC_LOCKING);
    // SNAPSHOT_RESTORE deliberately absent: H2's SCRIPT/RUNSCRIPT is a dump and a replay, not a
    // point-in-time snapshot the platform can restore to, and declaring it would be a promise the
    // generator trusts wrongly. The platform's own SchemaDropSnapshotWriter is an application-level
    // copy and does not make this an engine capability.

    private final UpsertStrategy upsert = new H2UpsertStrategy();
    private final ReturningStrategy returning = new H2ReturningStrategy();

    private H2Dialect() {
    }

    @Override
    public String name() {
        return "h2";
    }

    @Override
    public String quoteIdentifier(String rawIdentifier) {
        Objects.requireNonNull(rawIdentifier, "rawIdentifier");
        return '"' + rawIdentifier.replace("\"", "\"\"") + '"';
    }

    @Override
    public boolean isReservedIdentifier(String rawIdentifier) {
        return SqlReservedWords.isReserved(name(), rawIdentifier);
    }

    @Override
    public boolean foldsUnquotedIdentifiersToLowerCase() {
        // In PostgreSQL compatibility mode with DATABASE_TO_LOWER, which is how NPDev runs H2.
        return true;
    }

    @Override
    public String autoIncrementColumn(SqlType type) {
        return switch (type) {
            case INT -> "INT GENERATED BY DEFAULT AS IDENTITY";
            case BIGINT -> "BIGINT GENERATED BY DEFAULT AS IDENTITY";
            default -> throw new IllegalArgumentException(
                    "engine 'h2': " + type + " cannot be an auto-increment column; use INT or BIGINT");
        };
    }

    @Override
    public String jsonColumnType() {
        // JSONB has no H2 equivalent; H2 has JSON. This is the mapping ConversionHookEmitter and
        // SchemaRealizationEmitter each spelled by hand at generation time.
        return "JSON";
    }

    @Override
    public boolean isJsonColumnType(String sqlTypeName) {
        return sqlTypeName != null && JSON_TYPE_NAMES.contains(sqlTypeName.trim().toLowerCase(Locale.ROOT));
    }

    /** H2 indexes VARCHAR happily and has no key-length restriction; bounded anyway so every
     *  engine realizes the SAME column type and a later schema diff has nothing to explain. */
    @Override
    public String keyableTextColumnType() {
        return "VARCHAR(191)";
    }

    @Override
    public String defaultableTextColumnType() {
        // H2 carries a DEFAULT on its unbounded text type without complaint, so the payload
        // answer is also the defaulted answer -- narrowing here would change a column type on an
        // engine that never had the problem.
        return portableColumnType("TEXT");
    }

    @Override
    public String selectForUpdate(String columns, String table, String whereClause) {
        return "SELECT " + columns + " FROM " + table + " WHERE " + whereClause + " FOR UPDATE";
    }

    @Override
    public String renameColumn(String table, String from_, String to) {
        return "ALTER TABLE " + identifier(table) + " ALTER COLUMN " + identifier(from_)
                + " RENAME TO " + identifier(to);
    }

    @Override
    public boolean isUniqueViolation(java.sql.SQLException failure) {
        if (failure == null) {
            return false;
        }
        // H2 reports 23505 like Postgres (and 23001 for a unique INDEX in some versions).
        for (java.sql.SQLException current = failure; current != null;
                current = current.getNextException()) {
            String state = current.getSQLState();
            if ("23505".equals(state) || "23001".equals(state)) {
                return true;
            }
        }
        return false;
    }

    @Override
    public String timestampColumnType() {
        return "TIMESTAMP WITH TIME ZONE";
    }

    @Override
    public String portableColumnType(String declaredSqlType) {
        if (declaredSqlType == null) {
            return null;
        }
        String normalized = declaredSqlType.trim();
        // JSONB has no H2 equivalent; H2 has JSON. Every other SqlTypeSupport#sqlType result is
        // already identical on H2 and Postgres (confirmed by the schema engine's own renderType and
        // addBackfillAndTightenColumn precedents), so the list is deliberately short rather than a
        // speculative mapping table.
        if ("JSONB".equalsIgnoreCase(normalized) || "JSON".equalsIgnoreCase(normalized)) {
            return "JSON";
        }
        if ("TIMESTAMP WITH TIME ZONE".equalsIgnoreCase(normalized)) {
            return "TIMESTAMP WITH TIME ZONE";
        }
        return normalized;
    }

    @Override
    public PaginationClause limitOffset() {
        return new PaginationClause(LIMIT_OFFSET_CLAUSE,
                List.of(PaginationClause.Parameter.LIMIT, PaginationClause.Parameter.OFFSET));
    }

    @Override
    public PaginationClause limitOnly() {
        return new PaginationClause(LIMIT_ONLY_CLAUSE, List.of(PaginationClause.Parameter.LIMIT));
    }

    @Override
    public String rowLimit(long rows) {
        if (rows <= 0) {
            throw new IllegalArgumentException("engine 'h2': rowLimit must be positive, got " + rows);
        }
        return ROW_LIMIT_PREFIX + rows;
    }

    @Override
    public UpsertStrategy upsert() {
        return upsert;
    }

    @Override
    public ReturningStrategy returning() {
        return returning;
    }

    @Override
    public String cast(String expression, SqlType type) {
        return "CAST(" + expression + " AS " + castTypeName(type) + ")";
    }

    private static String castTypeName(SqlType type) {
        return switch (type) {
            case TEXT -> "VARCHAR";
            case INT -> "INT";
            case BIGINT -> "BIGINT";
            case UUID -> "UUID";
            case BOOLEAN -> "BOOLEAN";
            case NUMERIC -> "NUMERIC";
            case TIMESTAMP -> "TIMESTAMP WITH TIME ZONE";
            case JSON -> "JSON";
            case BLOB -> "VARBINARY";
        };
    }

    @Override
    public Set<String> systemSchemas() {
        return SYSTEM_SCHEMAS;
    }

    @Override
    public String listTablesSql() {
        return "SELECT table_name FROM information_schema.tables"
                + " WHERE table_schema = COALESCE(?, current_schema())"
                + " AND table_type = 'BASE TABLE' ORDER BY table_name";
    }

    @Override
    public String listColumnsSql() {
        return "SELECT column_name, data_type, is_nullable, column_default"
                + " FROM information_schema.columns"
                + " WHERE table_schema = COALESCE(?, current_schema()) AND table_name = ?"
                + " ORDER BY ordinal_position";
    }

    @Override
    public String listIndexesSql() {
        // H2 2.x moved index metadata to INFORMATION_SCHEMA.INDEXES + INDEX_COLUMNS; there is no
        // pg_index here, so this is genuinely a different query rather than a reworded one.
        // Uniqueness comes from INDEX_TYPE_NAME ('UNIQUE INDEX' / 'PRIMARY KEY' / 'INDEX') -- getting
        // that wrong is REG-129's exact bug class, which conformance I3 exists to catch.
        return "SELECT i.index_name AS index_name,"
                + " ic.column_name AS column_name,"
                + " CASE WHEN i.index_type_name IN ('UNIQUE INDEX', 'PRIMARY KEY')"
                + " THEN TRUE ELSE FALSE END AS is_unique"
                + " FROM information_schema.indexes i"
                + " JOIN information_schema.index_columns ic"
                + " ON ic.index_name = i.index_name AND ic.table_name = i.table_name"
                + " WHERE i.table_schema = COALESCE(?, current_schema()) AND i.table_name = ?"
                + " ORDER BY i.index_name, ic.ordinal_position";
    }

    @Override
    public String tableExistsInCurrentSchemaSql(String tableName) {
        return "SELECT COUNT(*) FROM information_schema.tables"
                + " WHERE LOWER(table_schema) = LOWER(CURRENT_SCHEMA())"
                + " AND LOWER(table_name) = '" + escapeLiteral(tableName).toLowerCase(Locale.ROOT) + "'";
    }

    @Override
    public String constraintExistsSql() {
        return "SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS "
                + "WHERE UPPER(CONSTRAINT_NAME) = UPPER(?) AND UPPER(TABLE_NAME) = UPPER(?)";
    }

    /*
     * ------------------------------------------------------------------------------------------
     * STOR-5's three guarded idioms. This engine has them natively, so each returns the SAME TEXT
     * the emitter used to write inline -- which is the regression guard: extracting these must not
     * change one byte of H2 output, and PostgresDialectGoldenSqlTest is what proves it.
     * ------------------------------------------------------------------------------------------
     */

    @Override
    public String guardedCreateTable(String tableName, String createStatement) {
        return SqlDdlGuards.insertAfter(createStatement, "CREATE TABLE", "IF NOT EXISTS");
    }

    @Override
    public String guardedCreateIndex(String indexName, String tableName, String createStatement) {
        return SqlDdlGuards.insertAfterIndexKeyword(createStatement, "IF NOT EXISTS");
    }

    @Override
    public String guardedAddColumn(String tableName, String columnName, String alterStatement) {
        return SqlDdlGuards.insertAfter(alterStatement, "ADD COLUMN", "IF NOT EXISTS");
    }

    @Override
    public String guardedConstraintDdl(String constraintName, String tableName, String ddlStatement) {
        // REG-38: this lands in R__npdev_schema_additive_columns.sql, a Flyway *repeatable* migration
        // that re-runs whenever its checksum changes (any model edit regenerates it). A bare
        // "ADD CONSTRAINT" is not idempotent -- the re-run against a DB that already has the
        // constraint fails with "Constraint already exists" and refuses the whole boot. H2 supports
        // "DROP CONSTRAINT IF EXISTS", so drop-then-add makes the statement idempotent the same way
        // Postgres's catalog-guarded DO $$ block is. Genuinely a different shape, not a reworded one,
        // which is why this is a dialect method rather than a shared template.
        String statement = ddlStatement.endsWith(";") ? ddlStatement : ddlStatement + ";";
        return "ALTER TABLE " + tableName + " DROP CONSTRAINT IF EXISTS " + constraintName + ";\n"
                + statement + "\n";
    }

    private static String schemaPredicate(String schema) {
        return schema == null || schema.isBlank() ? "current_schema()" : "'" + escapeLiteral(schema) + "'";
    }

    private static String escapeLiteral(String value) {
        return value == null ? "" : value.replace("'", "''");
    }

    @Override
    public Set<StorageCapability> capabilities() {
        return CAPABILITIES;
    }

    @Override
    public String toString() {
        return "SqlDialect[h2]";
    }

    /**
     * {@code MERGE INTO t (cols) KEY(k) VALUES (?, ...)}.
     *
     * <p>H2's MERGE takes no update list: matching rows are replaced wholesale by the supplied values.
     * That is the shape both pre-extraction sites emitted.
     */
    static final class H2UpsertStrategy implements UpsertStrategy {

        private static String quoted(String rawIdentifier) {
            return H2Dialect.INSTANCE.identifier(rawIdentifier);
        }

        private static List<String> quotedAll(List<String> rawIdentifiers) {
            return H2Dialect.INSTANCE.identifiers(rawIdentifiers);
        }
        @Override
        public String statementFor(String rawTable, List<String> keyColumns, List<String> valueColumns) {
            // STOR-6: quote HERE, as the text is composed. The caller keeps raw names for
            // its map lookups, and bindColumns() must echo those back unquoted.
            String table = H2Dialect.INSTANCE.identifier(rawTable);
            if (keyColumns == null || keyColumns.isEmpty()) {
                throw new IllegalArgumentException("engine 'h2': upsert needs at least one key column");
            }
            if (valueColumns == null || valueColumns.isEmpty()) {
                throw new IllegalArgumentException("engine 'h2': upsert needs at least one value column");
            }
            String placeholders = String.join(", ", java.util.Collections.nCopies(valueColumns.size(), "?"));
            return "MERGE INTO " + table
                    + " (" + String.join(", ", quotedAll(valueColumns)) + ")"
                    + " KEY(" + String.join(", ", quotedAll(keyColumns)) + ")"
                    + " VALUES (" + placeholders + ")";
        }
    }

    /** H2 in PostgreSQL mode accepts RETURNING on INSERT. */
    static final class H2ReturningStrategy implements ReturningStrategy {
        @Override
        public boolean isInline() {
            return true;
        }

        @Override
        public String inlineClause(List<String> columns) {
            if (columns == null || columns.isEmpty()) {
                throw new IllegalArgumentException("engine 'h2': RETURNING needs at least one column");
            }
            return "RETURNING " + String.join(", ", columns);
        }

        @Override
        public String secondQuerySql() {
            throw new UnsupportedOperationException(
                    "engine 'h2': generated keys come back inline. Check isInline() and use inlineClause(...).");
        }
    }
}
