<#
.SYNOPSIS
  Write `starter.html` at the output root: the app's own generated info page plus a LOCAL overlay of
  the facts only this machine knows.

.DESCRIPTION
  MONITOR_PLAN D2-a. This script used to be a SECOND RENDERER: it built its own 38-row page and
  overwrote the one `InfoPageEmitter` had just emitted, so an ops-wrapper build and a plain
  generation produced different pages for the same app. Worse, its rows included absolute paths
  (`D:\...\Build-AppGenApp.ps1` among them) baked straight into generated output -- the defect PORT-1
  spent 2026-08-10 removing from six emitters.

  It no longer renders anything. `info.html` and `info.json` belong to the emitter and are left
  exactly as generated -- portable, zero absolute paths, identical whichever way the app was built.

  What this script still adds is real and worth keeping: the LOCAL rows. The jar, the ops toolbox,
  the app definition, the model, the database file, the super-user key file are what makes the page
  useful while you are working on this machine, and they are precisely the rows that must not be
  baked into an artefact somebody else might open. So they go into `starter.html` only -- a file at
  the BUILD output root, next to the paths it names, which is never copied anywhere as part of the
  app -- inside a `<script type="application/json" id="npdev-local">` block that the emitted page
  already knows how to render. One renderer, two data sources.

  `starter.html` is openable via `file://` while the app is OFF, which is why the emitted page embeds
  its JSON rather than fetching it (D2-b): `fetch()` from a `file://` origin is blocked by every
  browser, so a fetch-based page renders EMPTY in exactly the state a user is diagnosing.

  The authoritative live view of the same local facts is `npdev monitor probe --app-dir <app>`,
  which the Monitor's inspector overlays onto this same page structure.
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)][string]$StaticDir,
  [Parameter(Mandatory = $true)][string]$AppId,
  [Parameter(Mandatory = $true)][int]$Port,
  [Parameter(Mandatory = $true)][string]$AppFolder,
  [Parameter(Mandatory = $true)][string]$OutRoot,
  [Parameter(Mandatory = $true)][string]$GeneratedAppRoot,
  [Parameter(Mandatory = $true)][string]$OpsDir,
  [string]$Engine = 'InMemory',
  [string]$JdbcUrl = '',
  [string]$DbDataRoot = '',
  [string]$DbName = '',
  [string[]]$Flows = @(),
  [string[]]$Concepts = @(),
  [string[]]$CompanionFiles = @(),
  [string]$BuilderName = '',
  [string]$ConsoleLaunch = '',
  [int]$ConsolePort = 0,
  [string]$LoginPath = '',
  [string]$HomePath = ''
)
$ErrorActionPreference = 'Stop'

# The emitter writes into the GENERATED source set (`npdev-generated/...`), which is where the
# platform's own artefacts live and which the strict-execution validator hashes -- so nothing here
# ever writes into it. `$StaticDir` is the APP MODULE's handwritten static dir, and it is only ever
# read, or cleaned, below.
$emittedStatic = Join-Path $GeneratedAppRoot 'npdev-generated\src\main\resources\static'
$infoHtml = Join-Path $emittedStatic 'info.html'
$handwrittenInfoHtml = Join-Path $StaticDir 'info.html'

if (-not (Test-Path -LiteralPath $infoHtml)) {
  # An honest refusal rather than quietly re-inventing the page. A missing info.html means the app
  # was generated by a generator older than the emitter, and the fix is to regenerate -- not to have
  # this script produce a lookalike that then diverges from every other app's.
  Write-Warning ("No generated info.html at $infoHtml -- this app predates InfoPageEmitter. " +
                 "Regenerate it to get the info page; starter.html was not written.")
  return
}

# MEASURED 2026-08-10, on a clean `gradlew clean processResources`: when both source sets carry
# `static/info.html`, the HANDWRITTEN one wins. (`processResources` lists `npdev-generated` first and
# `src/main/resources` last under DuplicatesStrategy.EXCLUDE, and the last-listed copy is the one
# that ends up packaged.)
#
# So while this script still wrote its own page, an ops-wrapper build shipped THAT page and a plain
# generation shipped the emitter's -- the same app, two different info pages, decided by which
# builder happened to run. That is the divergence D2-a exists to kill, and it has been live since
# the emitter landed in beta1.14. Removing a stale copy left by an earlier build is what makes the
# kill stick: leaving it would silently shadow the emitted page forever.
if (Test-Path -LiteralPath $handwrittenInfoHtml) {
  Write-Verbose "Removing a stale handwritten info.html that would shadow the generated one: $handwrittenInfoHtml"
  Remove-Item -LiteralPath $handwrittenInfoHtml -Force
}

# ---- the LOCAL overlay: rows only this machine can know -------------------------------------
$rows = New-Object System.Collections.Generic.List[object]
function Add-LocalRow([string]$Section, [string]$Property, [string]$Value, [bool]$Important = $false) {
  if ([string]::IsNullOrWhiteSpace($Value)) { return }
  $rows.Add([ordered]@{ section = $Section; property = $Property; value = "$Value"
                        openable = $false; important = $Important })
}

Add-LocalRow 'Local paths (this machine)' 'App definition'        $AppFolder
Add-LocalRow 'Local paths (this machine)' 'Model'                 (Join-Path $AppFolder 'definition\model.json')
Add-LocalRow 'Local paths (this machine)' 'Generated output root' $OutRoot
Add-LocalRow 'Local paths (this machine)' 'Generated app'         $GeneratedAppRoot
Add-LocalRow 'Local paths (this machine)' 'Runnable jar'          (Join-Path $GeneratedAppRoot 'build\libs\FinalExec-0.1.0.jar')
Add-LocalRow 'Local paths (this machine)' 'Ops toolbox'           $OpsDir
Add-LocalRow 'Local paths (this machine)' 'Run logs'              (Join-Path $GeneratedAppRoot 'logs')
Add-LocalRow 'Local paths (this machine)' 'Super User key file'   (Join-Path $OpsDir 'SUPER_USER_KEY.txt') $true
if ($Engine -eq 'H2Server' -and $DbName) {
  Add-LocalRow 'Local paths (this machine)' 'DB file' (Join-Path $DbDataRoot "$DbName.mv.db")
}

# The connection block stays LOCAL and stays out of info.json for one blunt reason: info.json is
# served unauthenticated (static content is exempt from the API-key filter), so publishing a JDBC URL
# and credentials there would hand them to anyone who can reach the app.
if ($Engine -eq 'H2Server') {
  Add-LocalRow 'Local database' 'JDBC URL'          $JdbcUrl
  Add-LocalRow 'Local database' 'DB user / password' 'sa / (empty)'
  Add-LocalRow 'Local database' 'DB driver'         'org.h2.Driver 2.2.224'
}
elseif ($Engine -ne 'InMemory') {
  Add-LocalRow 'Local database' 'JDBC URL' $JdbcUrl
}
else {
  Add-LocalRow 'Local database' 'DB access' 'in-process, not externally reachable'
}

# REG-144 / PORT-1: the builder path is DERIVED from where this script actually lives, never typed.
# The previous version wrote `D:\WorkSpace\NPDev\NPDev_General\scripts\appgen\Build-AppGenApp.ps1`
# into every generated app -- a drive that exists on one machine, in a file whose whole point is
# telling somebody what to run.
$builderScript = Join-Path $PSScriptRoot 'Build-AppGenApp.ps1'
Add-LocalRow 'Local commands' 'Builder script' $builderScript
if ($BuilderName) { Add-LocalRow 'Local commands' 'Generate cmd' ("& '" + $builderScript + "' -App " + $BuilderName) }
foreach ($pair in @(
    @{ n = 'Build cmd'; f = 'Build-FinalApp.ps1' },
    @{ n = 'Run cmd';   f = 'Run-FinalApp.ps1' },
    @{ n = 'Smoke cmd'; f = 'Smoke-Test.ps1' },
    @{ n = 'Stop cmd';  f = 'Stop-Environment.ps1' })) {
  Add-LocalRow 'Local commands' $pair.n ("& '" + (Join-Path $OpsDir $pair.f) + "'")
}
Add-LocalRow 'Local commands' 'Probe this app' ("npdev monitor probe --app-dir '" + $GeneratedAppRoot + "'")
Add-LocalRow 'Local commands' 'Read its logs'  ("npdev monitor logs --app-dir '" + $GeneratedAppRoot + "'")
if ($ConsoleLaunch) { Add-LocalRow 'Local commands' 'Console (local)' $ConsoleLaunch }

foreach ($f in $CompanionFiles) {
  Add-LocalRow 'Companion files' ("Companion " + $f) ("http://localhost:$Port/" + $f)
}

# `@($rows)` (converting the List[object] via the array subexpression operator) hits a PowerShell
# 7.5/.NET 9 dynamic-binder regression here: `PSToObjectArrayBinder`/`PSEnumerableBinder.MaybeDebase`
# throws "Argument types do not match" (a LINQ `Expression.Condition` failure inside PowerShell's own
# runtime, not this script) the moment the list holds `[ordered]` dictionaries. `.ToArray()` on the
# List[object] produces the identical object[] without going through that binder.
$overlay = [ordered]@{
  schemaVersion = 'npdev-app-info-local.v1'
  generatedBy   = 'scripts/appgen/New-AppInfoPage.ps1'
  appId         = $AppId
  note          = 'Facts about THIS MACHINE. Deliberately absent from the app''s own info.json, which travels.'
  records       = $rows.ToArray()
}
$overlayJson = ($overlay | ConvertTo-Json -Depth 6)
# Same escape the emitter applies: a value containing a literal </script> must not close the tag.
$overlayJson = $overlayJson.Replace('</', '<\/')

$html = Get-Content -Raw -LiteralPath $infoHtml
$injection = "<script type=""application/json"" id=""npdev-local"">$overlayJson</script>`n</body>"
if ($html -notmatch '</body>') {
  Write-Warning "Generated info.html has no </body> to inject the local overlay before; starter.html will carry portable rows only."
  $starter = $html
}
else {
  $starter = $html -replace '</body>', $injection
}

# starter.html only. info.html and info.json are the emitter's, and overwriting them is precisely
# the divergence D2-a exists to kill: an ops-wrapper build and a plain generation must produce the
# same page for the same app.
Set-Content -LiteralPath (Join-Path $OutRoot 'starter.html') -Value $starter -Encoding UTF8
