<#
.SYNOPSIS
  Emit a local control console (Serve-AppConsole.ps1 + console.html) for a generated app.

.DESCRIPTION
  Writes a self-contained local web console into the app's _ops folder:
    - Serve-AppConsole.ps1 : a 127.0.0.1-only HttpListener server (no installs) that runs the
      whitelisted _ops scripts (Status/Build/Start/Test/Stop) and streams stdout/stderr to the
      page via Server-Sent Events. Token-guarded (random per launch).
    - console.html         : the terminal-style page (buttons + live output + optional filter).

  Mode (from config.json `console.mode`, passed as -Mode):
    whitelist            -> only the 5 fixed ops actions
    whitelist-freeform   -> the 5 ops actions + a free-form PowerShell command box (RCE surface;
                            only for a trusted local machine)
    none                 -> this helper is not called (no console emitted)

  Security: binds to 127.0.0.1 only, requires the token, and (in whitelist mode) maps a fixed
  set of action ids to a fixed set of scripts. See source-of-truth-layers / appgen recipe memory.
#>
[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)][string]$OpsDir,
  [Parameter(Mandatory = $true)][string]$AppId,
  [Parameter(Mandatory = $true)][int]$ConsolePort,
  [Parameter(Mandatory = $true)][string]$OutRoot,
  [ValidateSet('whitelist','whitelist-freeform')][string]$Mode = 'whitelist'
)
$ErrorActionPreference = 'Stop'
New-Item -ItemType Directory -Force -Path $OpsDir | Out-Null

$serve = @'
<#  Local control console for @@APPID@@ - generated by New-AppConsole.ps1.
    Serves a token-guarded page on 127.0.0.1 that runs the whitelisted _ops scripts. #>
[CmdletBinding()]
param([int]$Port = @@CONSOLEPORT@@, [switch]$NoBrowser)
$ErrorActionPreference = 'Stop'
$AppId  = '@@APPID@@'
$OpsDir = '@@OPSDIR@@'
$OutRoot = '@@OUTROOT@@'
$Mode   = '@@MODE@@'
$AllowFreeform = ($Mode -eq 'whitelist-freeform')

# Fixed whitelist: action id -> _ops script (+ args). This is the security boundary.
$actions = [ordered]@{
  status = @{ label = 'Status'; file = 'Status-App.ps1'; args = @() }
  build  = @{ label = 'Build';  file = 'Build-App.ps1';  args = @('-Force') }
  start  = @{ label = 'Start';  file = 'Start-App.ps1';  args = @() }
  test   = @{ label = 'Test';   file = 'Test-App.ps1';   args = @() }
  stop   = @{ label = 'Stop';   file = 'Stop-App.ps1';   args = @() }
}

$token = [guid]::NewGuid().ToString('N')
$listener = [System.Net.HttpListener]::new()
$prefix = "http://127.0.0.1:$Port/"
$listener.Prefixes.Add($prefix)
try { $listener.Start() } catch { Write-Host "Failed to bind $prefix : $($_.Exception.Message)" -ForegroundColor Red; exit 1 }
$consoleUrl = "http://127.0.0.1:$Port/?token=$token"
Write-Host ''
Write-Host "NPDev control console for $AppId" -ForegroundColor Green
Write-Host "  URL : $consoleUrl"
Write-Host "  Mode: $Mode  (freeform: $AllowFreeform)"
Write-Host '  Stop the console with Ctrl+C.'
if (-not $NoBrowser) { try { Start-Process $consoleUrl | Out-Null } catch {} }

function Send-Bytes($res, [string]$text, [int]$code = 200, [string]$type = 'text/plain; charset=utf-8') {
  $res.StatusCode = $code; $res.ContentType = $type
  $b = [Text.Encoding]::UTF8.GetBytes($text)
  $res.OutputStream.Write($b, 0, $b.Length); $res.OutputStream.Close()
}

function Get-AppStatus {
  # Colors: running=green, paused=grey, error=red, warning=yellow, notbuilt=cyan
  $base = ''; $key = 'dev-key'; $appRoot = ''
  $planPath = Join-Path $OpsDir 'app-plan.json'
  if (Test-Path -LiteralPath $planPath) { try { $pl = Get-Content -Raw -LiteralPath $planPath | ConvertFrom-Json; $base = "$($pl.baseUrl)"; $key = "$($pl.apiKey)"; $appRoot = "$($pl.appRoot)" } catch {} }
  # REG-152: $pl.apiKey is a generation-time-only placeholder once Ensure-NpdevApiKey has run (R7
  # Stage C/REG-152 fix) -- the live, working key lives in secrets/api-key.env. Prefer it when
  # present, same redirect Stage C already applied to npdev_monitor.py's probe_app().
  if ($appRoot) {
    $liveKeyFile = Join-Path $appRoot 'secrets\api-key.env'
    if (Test-Path -LiteralPath $liveKeyFile) {
      try {
        foreach ($rawLine in (Get-Content -LiteralPath $liveKeyFile)) {
          $line = $rawLine.Trim()
          if ($line -and -not $line.StartsWith('#') -and $line.Contains('=')) {
            $mapping = $line.Split('=', 2)[1]
            $key = $mapping.Split('=', 2)[0]
            break
          }
        }
      } catch {}
    }
  }
  $jar = $null
  if ($appRoot) { $jar = Get-ChildItem -Path (Join-Path $appRoot 'build\libs') -Filter 'FinalExec-*.jar' -ErrorAction SilentlyContinue | Where-Object { $_.Name -notlike '*-plain.jar' } | Select-Object -First 1 }
  $reachable = $false
  if ($base) { try { Invoke-RestMethod -Uri "$base/api/flows" -Headers @{ 'X-Api-Key' = $key } -TimeoutSec 2 | Out-Null; $reachable = $true } catch {} }
  $hardError = $false
  $outlog = Join-Path $OpsDir 'app.out.log'
  if (-not $reachable -and (Test-Path -LiteralPath $outlog)) { try { $tail = (Get-Content -LiteralPath $outlog -Tail 150) -join "`n"; if ($tail -match 'APPLICATION FAILED TO START|Application run failed') { $hardError = $true } } catch {} }
  $smokeFail = $false
  $smoke = Join-Path $OpsDir 'smoke-test-report.json'
  if (Test-Path -LiteralPath $smoke) { try { $smokeFail = ((Get-Content -Raw -LiteralPath $smoke | ConvertFrom-Json).status -eq 'FAIL') } catch {} }
  if ($reachable) { $state = if ($smokeFail) { 'warning' } else { 'running' } }
  elseif (-not $jar) { $state = 'notbuilt' }
  elseif ($hardError -or $smokeFail) { $state = 'error' }
  else { $state = 'paused' }
  $colors = @{ running = '#2ecc71'; paused = '#9aa0a6'; error = '#e74c3c'; warning = '#f1c40f'; notbuilt = '#00bcd4' }
  $details = @{ running = 'app is up'; paused = 'built, not running'; error = 'last run/build had errors'; warning = 'up but tests failing'; notbuilt = 'not built yet' }
  return @{ state = $state; color = $colors[$state]; detail = $details[$state] }
}

while ($listener.IsListening) {
  $ctx = $listener.GetContext()
  $req = $ctx.Request; $res = $ctx.Response
  try {
    $path = $req.Url.AbsolutePath

    # The page at '/' is served WITHOUT a token (so it can be embedded as an iframe). It
    # embeds the live token internally; /status and /run below still require the token, which
    # is what actually protects against cross-site requests (the token can't be read cross-origin).
    if ($path -eq '/') {
      $items = @($actions.GetEnumerator() | ForEach-Object { [pscustomobject]@{ id = $_.Key; label = $_.Value.label } })
      $actionsJson = $items | ConvertTo-Json -Compress
      if ($items.Count -eq 1) { $actionsJson = "[$actionsJson]" }
      $tpl = Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot 'console.html')
      $html = $tpl.Replace('__TOKEN__', $token).Replace('__APPID__', $AppId).Replace('__ACTIONS__', $actionsJson).Replace('__FREEFORM__', $(if ($AllowFreeform) { 'true' } else { 'false' }))
      Send-Bytes $res $html 200 'text/html; charset=utf-8'
      continue
    }

    # everything except the page itself requires the token
    if ($req.QueryString['token'] -ne $token) { Send-Bytes $res 'forbidden' 403; continue }

    if ($path -eq '/status') {
      $st = Get-AppStatus
      Send-Bytes $res ($st | ConvertTo-Json -Compress) 200 'application/json; charset=utf-8'
      continue
    }

    if ($path -eq '/run') {
      $action = "$($req.QueryString['action'])"
      $psCmd = $null
      if ($actions.Contains($action)) {
        $sf = Join-Path $OpsDir $actions[$action].file
        $extra = ($actions[$action].args -join ' ')
        $psCmd = "& '$sf' $extra *>&1"
      } elseif ($action -eq 'exec' -and $AllowFreeform) {
        $cmd = "$($req.QueryString['cmd'])"
        if (-not [string]::IsNullOrWhiteSpace($cmd)) { $psCmd = "$cmd *>&1" }
      }

      $res.StatusCode = 200; $res.ContentType = 'text/event-stream'
      $res.Headers.Add('Cache-Control', 'no-cache')
      $sw = [IO.StreamWriter]::new($res.OutputStream, [Text.UTF8Encoding]::new($false))
      $sw.NewLine = "`n"
      $emit = { param($line) $sw.Write("data: " + (($line -replace "`r", '') -replace "`n", '') + "`n`n"); $sw.Flush() }

      if (-not $psCmd) {
        & $emit "[console] action not allowed: $action"
        $sw.Write("event: done`ndata: 1`n`n"); $sw.Flush(); $res.OutputStream.Close(); continue
      }

      & $emit "[console] running: $action"
      $exit = 0
      try {
        # Run the action in a child pwsh and stream merged output. Uses the call operator +
        # pipeline (works in both Windows PowerShell 5.1 and PowerShell 7; avoids
        # ProcessStartInfo.ArgumentList, which is null on .NET Framework). The child's own
        # 'exit' only ends the child, not this server.
        & pwsh -NoProfile -ExecutionPolicy Bypass -Command $psCmd 2>&1 | ForEach-Object { & $emit "$_" }
        $exit = $LASTEXITCODE
        if ($null -eq $exit) { $exit = 0 }
      } catch {
        & $emit "[console] error: $($_.Exception.Message)"; $exit = 1
      }
      $sw.Write("event: done`ndata: $exit`n`n"); $sw.Flush()
      $res.OutputStream.Close()
      continue
    }

    Send-Bytes $res 'not found' 404
  } catch {
    try { Send-Bytes $res "error: $($_.Exception.Message)" 500 } catch {}
  }
}
'@

$page = @'
<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>__APPID__ - console</title>
<style>
 :root{--bg:#0c0c0c}
 *{box-sizing:border-box}
 body{margin:0;background:var(--bg);color:#eee;font-family:system-ui,sans-serif}
 header{display:flex;gap:8px;align-items:center;flex-wrap:wrap;padding:10px 14px;background:#1b1b1b}
 header b{font-size:15px}
 header .sp{margin-left:auto;opacity:.6;font-size:12px}
 button{background:#2d6cdf;color:#fff;border:0;border-radius:5px;padding:6px 12px;cursor:pointer;font-size:13px}
 button.sec{background:#333}
 button:disabled{opacity:.5;cursor:default}
 .ff{display:flex;gap:6px;padding:8px 14px;background:#161616;border-top:1px solid #222}
 .ff input{flex:1;background:#000;color:#cde;border:1px solid #444;border-radius:5px;padding:6px 8px;font-family:monospace}
 #term{margin:0;padding:12px 14px;height:calc(100vh - 110px);overflow:auto;white-space:pre-wrap;word-break:break-word;
       font-family:Consolas,monospace;font-size:13px;line-height:1.4;color:#cfe3ff;background:var(--bg)}
 .muted{opacity:.55}
 .dot{width:13px;height:13px;border-radius:50%;background:#555;display:inline-block;box-shadow:0 0 6px rgba(0,0,0,.6)}
</style></head><body>
<header>
  <span id="dot" class="dot" title="status"></span>
  <b>__APPID__</b> <span class="muted">console</span> <span id="appstate" class="muted"></span>
  <span id="btns"></span>
  <button class="sec" onclick="clearTerm()">Clear</button>
  <span class="sp" id="status">idle</span>
</header>
<div class="ff" id="ffbox" style="display:none">
  <input id="ff" placeholder="PowerShell command (free-form mode)..." onkeydown="if(event.key==='Enter')runFree()">
  <button onclick="runFree()">Run</button>
</div>
<pre id="term"></pre>
<script>
const TOKEN='__TOKEN__'; const ACTIONS=__ACTIONS__; const FREEFORM=__FREEFORM__;
const term=document.getElementById('term'); const statusEl=document.getElementById('status');
let es=null;
function line(t){ const atBottom = term.scrollTop+term.clientHeight >= term.scrollHeight-4; term.textContent += t+'\n'; if(atBottom) term.scrollTop=term.scrollHeight; }
function clearTerm(){ term.textContent=''; }
function setBusy(b){ document.querySelectorAll('#btns button,.ff button').forEach(x=>x.disabled=b); statusEl.textContent=b?'running...':'idle'; }
function stream(url,label){
  if(es){es.close();}
  setBusy(true); line('\n$ '+label);
  es=new EventSource(url);
  es.onmessage=e=>line(e.data);
  es.addEventListener('done',e=>{ line('[exit '+e.data+']'); es.close(); es=null; setBusy(false); });
  es.onerror=()=>{ if(es){es.close();es=null;} setBusy(false); statusEl.textContent='disconnected'; };
}
function run(id,label){ stream('/run?action='+encodeURIComponent(id)+'&token='+TOKEN, label); }
function runFree(){ const v=document.getElementById('ff').value.trim(); if(!v)return; stream('/run?action=exec&cmd='+encodeURIComponent(v)+'&token='+TOKEN, v); }
const btns=document.getElementById('btns');
ACTIONS.forEach(a=>{ const b=document.createElement('button'); b.textContent=a.label; b.onclick=()=>run(a.id,a.label); btns.appendChild(b); });
if(FREEFORM){ document.getElementById('ffbox').style.display='flex'; }
line('Ready. Whitelisted actions: '+ACTIONS.map(a=>a.label).join(', ')+(FREEFORM?'  + free-form':''));
async function poll(){ try{ const r=await fetch('/status?token='+TOKEN); const s=await r.json(); const d=document.getElementById('dot'); d.style.background=s.color; d.title='status: '+s.state+' - '+s.detail; document.getElementById('appstate').textContent='- '+s.state; }catch(e){} }
poll(); setInterval(poll, 3000);
</script></body></html>
'@

$serve = $serve.Replace('@@APPID@@', $AppId).Replace('@@OPSDIR@@', $OpsDir).Replace('@@OUTROOT@@', $OutRoot).Replace('@@MODE@@', $Mode).Replace('@@CONSOLEPORT@@', "$ConsolePort")
Set-Content -LiteralPath (Join-Path $OpsDir 'Serve-AppConsole.ps1') -Value $serve -Encoding UTF8
Set-Content -LiteralPath (Join-Path $OpsDir 'console.html') -Value $page -Encoding UTF8
