-- NPDev deterministic migration plan
-- Generated by MigrationScriptEmitter

CREATE TABLE IF NOT EXISTS contactmessages (id UUID PRIMARY KEY);
ALTER TABLE contactmessages ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE contactmessages ADD COLUMN IF NOT EXISTS id UUID;
ALTER TABLE contactmessages ADD COLUMN IF NOT EXISTS message VARCHAR(255);
ALTER TABLE contactmessages ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE contactmessages ADD COLUMN IF NOT EXISTS status VARCHAR(255);
ALTER TABLE contactmessages ALTER COLUMN email SET NOT NULL;
ALTER TABLE contactmessages ALTER COLUMN id SET NOT NULL;
ALTER TABLE contactmessages ALTER COLUMN message SET NOT NULL;
ALTER TABLE contactmessages ALTER COLUMN name SET NOT NULL;
ALTER TABLE contactmessages ALTER COLUMN status SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_contactmessages_id ON contactmessages (id);
