-- NPDev deterministic migration plan
-- Generated by MigrationScriptEmitter

ALTER TABLE users ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(255);
ALTER TABLE users ALTER COLUMN tenant_id SET NOT NULL;
