-- NPDev deterministic migration plan
-- Generated by MigrationScriptEmitter

CREATE TABLE IF NOT EXISTS expenserequests (id UUID PRIMARY KEY);
ALTER TABLE expenserequests ADD COLUMN IF NOT EXISTS amount INTEGER;
ALTER TABLE expenserequests ADD COLUMN IF NOT EXISTS employee_email VARCHAR(255);
ALTER TABLE expenserequests ADD COLUMN IF NOT EXISTS id UUID;
ALTER TABLE expenserequests ADD COLUMN IF NOT EXISTS needs_manager_approval BOOLEAN;
ALTER TABLE expenserequests ADD COLUMN IF NOT EXISTS status VARCHAR(255);
ALTER TABLE expenserequests ALTER COLUMN amount SET NOT NULL;
ALTER TABLE expenserequests ALTER COLUMN employee_email SET NOT NULL;
ALTER TABLE expenserequests ALTER COLUMN id SET NOT NULL;
ALTER TABLE expenserequests ALTER COLUMN needs_manager_approval SET NOT NULL;
ALTER TABLE expenserequests ALTER COLUMN status SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_expenserequests_id ON expenserequests (id);
