package com.npdev.generator.emitters;

import com.fasterxml.jackson.databind.JsonNode;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * deps-and-java/PLAN.md W2.2/D3: emits {@code npdev-dependencies.gradle} from config.json's
 * {@code build.repositories[]}/{@code build.dependencies[]} -- a generated SIDECAR file, not a
 * template edit, so {@code build.gradle.template} stays the byte-for-byte, substitution-free copy
 * it is documented as ({@code FinalAppAssembler#materializeRootTemplate}). An app with no
 * {@code build.dependencies}/{@code repositories} declared emits no sidecar at all and behaves
 * exactly as before this feature existed -- {@code build.gradle.template}'s own apply-from hook
 * (W2.3) is a no-op when the file is absent.
 */
public final class AppDependenciesEmitter {

    public static final String RELATIVE_PATH = "npdev-dependencies.gradle";
    private static final Pattern MATERIALIZED_DEPENDENCY_LINE = Pattern.compile(
            "^\\s*(?:implementation|runtimeOnly|compileOnly|testImplementation|api)\\s+(?:platform\\()?'([^:']+):([^:']+):"
    );

    public record EmitResult(boolean wroteFile, List<String> collisionWarnings) {
    }

    /**
     * @param runtimeHostAssembledBuildGradle the assembled app's OWN {@code build.gradle} (already
     *                                        materialized by {@code FinalAppAssembler} before this
     *                                        runs) -- read back rather than a hand-maintained
     *                                        collision list, so W2.5's warning can never silently
     *                                        drift from whatever RuntimeHost's template actually
     *                                        declares.
     */
    public EmitResult emit(JsonNode config, Path finalAppRoot, Path runtimeHostAssembledBuildGradle) throws Exception {
        JsonNode build = config == null ? null : config.path("build");
        List<JsonNode> repositories = toList(build == null ? null : build.path("repositories"));
        List<JsonNode> dependencies = toList(build == null ? null : build.path("dependencies"));

        if (repositories.isEmpty() && dependencies.isEmpty()) {
            return new EmitResult(false, List.of());
        }

        List<String> collisionWarnings = collisionWarnings(dependencies, runtimeHostAssembledBuildGradle);

        StringBuilder out = new StringBuilder();
        out.append("// Generated by NPDevGenerator (deps-and-java/PLAN.md W2.2) from config.json's build.\n");
        out.append("// repositories[]/dependencies[]. Re-run `npdev generate app` to pick up a config change --\n");
        out.append("// do not hand-edit; --cleanFinalApp/regeneration overwrites this file.\n\n");

        if (!repositories.isEmpty()) {
            out.append("repositories {\n");
            for (JsonNode repo : repositories) {
                String url = textOrNull(repo, "url");
                if (url == null) {
                    continue;
                }
                out.append("    maven { url '").append(escape(url)).append("' }\n");
            }
            out.append("}\n\n");
        }

        if (!dependencies.isEmpty()) {
            out.append("dependencies {\n");
            for (String warning : collisionWarnings) {
                out.append("    // WARNING: ").append(warning).append("\n");
            }
            for (JsonNode dep : dependencies) {
                out.append("    ").append(dependencyLine(dep)).append("\n");
            }
            out.append("}\n");
        }

        Path destination = finalAppRoot.resolve(RELATIVE_PATH);
        Files.createDirectories(destination.getParent());
        Files.writeString(destination, out.toString(), StandardCharsets.UTF_8);

        return new EmitResult(true, collisionWarnings);
    }

    /**
     * deps-and-java/PLAN.md W2.4/D4: {@code <modelSourceParent>/libs/*.jar} -- the SAME
     * definition-folder convention {@code <definition>/capabilities/<name>/src/main/java} already
     * uses for {@code plugin:java-source} -- copied flat into {@code <finalApp>/npdev-app-libs/} so
     * a {@code jar:} dependency entry (or a custom capability's own build) can reference them.
     * Copied at ASSEMBLY time (this method is called after {@code FinalAppAssembler.assemble}), not
     * baked into the generator's own deterministic output tree, for the same reason
     * {@code BuildInfoEmitter} runs where it does. Two guards, both non-optional: a jar cannot
     * resolve outside the definition root (mirrors {@code GeneratedPluginMountPlan}'s own
     * {@code startsWith(artifactRoot)} check), and a jar cannot be named
     * {@code npdev-migrations-*.jar} -- that name collides with
     * {@code enforceSingleSchemaRealizationSource} in build.gradle.template, which would otherwise
     * fail the build with a schema-realization error that has nothing to do with what the user did.
     */
    public List<String> copyLocalJars(Path modelPath, Path finalAppRoot) throws Exception {
        if (modelPath == null) {
            return List.of();
        }
        Path definitionRoot = modelPath.toAbsolutePath().normalize().getParent();
        if (definitionRoot == null) {
            return List.of();
        }
        Path libsDir = definitionRoot.resolve("libs");
        if (!Files.isDirectory(libsDir)) {
            return List.of();
        }

        List<String> copied = new ArrayList<>();
        Path destinationDir = finalAppRoot.resolve("npdev-app-libs");
        try (var stream = Files.list(libsDir)) {
            List<Path> jars = stream
                    .filter(p -> p.getFileName().toString().toLowerCase(Locale.ROOT).endsWith(".jar"))
                    .sorted()
                    .toList();
            for (Path jar : jars) {
                Path resolved = jar.toAbsolutePath().normalize();
                if (!resolved.startsWith(definitionRoot)) {
                    throw new IllegalArgumentException(
                            "Local jar resolved outside the model's own definition root: " + resolved
                                    + " (expected under " + definitionRoot + ")");
                }
                String fileName = resolved.getFileName().toString();
                if (fileName.toLowerCase(Locale.ROOT).matches("npdev-migrations-.*\\.jar")) {
                    throw new IllegalArgumentException(
                            "Local jar '" + fileName + "' under " + libsDir + " collides with the reserved "
                                    + "npdev-migrations-*.jar naming convention used by schema realization "
                                    + "(build.gradle.template's enforceSingleSchemaRealizationSource) -- rename it.");
                }
                Files.createDirectories(destinationDir);
                Files.copy(resolved, destinationDir.resolve(fileName), StandardCopyOption.REPLACE_EXISTING);
                copied.add(fileName);
            }
        }
        return copied;
    }

    private static String dependencyLine(JsonNode dep) {
        if (dep.isTextual()) {
            return "implementation '" + escape(dep.asText()) + "'";
        }

        String coordinate = textOrNull(dep, "coordinate");
        if (coordinate != null) {
            return scopeOrDefault(dep) + " '" + escape(coordinate) + "'";
        }

        String jar = textOrNull(dep, "jar");
        if (jar != null) {
            // W2.4 copies <modelSourceParent>/libs/*.jar flat into <finalApp>/npdev-app-libs/ --
            // only the file name survives, so reference it the same way here regardless of what
            // subdirectory (if any) the author's own libs/ declared it under.
            String fileName = Path.of(jar.replace('\\', '/')).getFileName().toString();
            return scopeOrDefault(dep) + " files('npdev-app-libs/" + escape(fileName) + "')";
        }

        String platform = textOrNull(dep, "platform");
        if (platform != null) {
            return "implementation platform('" + escape(platform) + "')";
        }

        throw new IllegalArgumentException(
                "config.json build.dependencies[] entry matched no known shape (coordinate/jar/platform/string): " + dep);
    }

    private static String scopeOrDefault(JsonNode dep) {
        String scope = textOrNull(dep, "scope");
        return scope == null ? "implementation" : scope;
    }

    /**
     * W2.5: named at generation time, not discovered as a runtime {@code NoSuchMethodError} four
     * layers deep. Compares each declared dependency's {@code groupId:artifactId} against every
     * {@code groupId:artifactId} the assembled app's OWN build.gradle already declares (Spring Boot
     * starters, Flyway, the NPDev-staged jars, etc.) -- read from the materialized file itself so
     * this can never silently drift from whatever RuntimeHost's template actually ships.
     */
    private static List<String> collisionWarnings(List<JsonNode> dependencies, Path assembledBuildGradle) {
        if (dependencies.isEmpty() || assembledBuildGradle == null || !Files.isRegularFile(assembledBuildGradle)) {
            return List.of();
        }

        Set<String> existingCoordinates = new LinkedHashSet<>();
        try {
            for (String line : Files.readAllLines(assembledBuildGradle, StandardCharsets.UTF_8)) {
                Matcher matcher = MATERIALIZED_DEPENDENCY_LINE.matcher(line);
                if (matcher.find()) {
                    existingCoordinates.add(matcher.group(1) + ":" + matcher.group(2));
                }
            }
        } catch (Exception e) {
            return List.of();
        }

        List<String> warnings = new ArrayList<>();
        for (JsonNode dep : dependencies) {
            String coordinate = dep.isTextual() ? dep.asText() : textOrNull(dep, "coordinate");
            if (coordinate == null) {
                continue;
            }
            String[] parts = coordinate.split(":");
            if (parts.length < 2) {
                continue;
            }
            String groupArtifact = parts[0] + ":" + parts[1];
            if (existingCoordinates.contains(groupArtifact)) {
                warnings.add("config.json declares " + coordinate + ", but " + groupArtifact
                        + " is already on this app's classpath (RuntimeHost's own build.gradle) -- "
                        + "the version actually used at compile/run time is whichever Gradle's own "
                        + "conflict resolution picks, not necessarily the one requested here.");
            }
        }
        return warnings;
    }

    private static List<JsonNode> toList(JsonNode arrayNode) {
        if (arrayNode == null || !arrayNode.isArray()) {
            return List.of();
        }
        List<JsonNode> items = new ArrayList<>();
        for (JsonNode item : arrayNode) {
            items.add(item);
        }
        return items;
    }

    private static String textOrNull(JsonNode node, String field) {
        JsonNode value = node.get(field);
        if (value == null || value.isNull() || !value.isTextual()) {
            return null;
        }
        String text = value.asText().trim();
        return text.isEmpty() ? null : text;
    }

    private static String escape(String value) {
        return value.replace("\\", "\\\\").replace("'", "\\'");
    }
}
