dependencies {
    api project(':core')
    implementation project(':dsl')
    testImplementation project(':adapters:persistence-postgres')
    testImplementation project(':adapters:events-inproc')
    testImplementation project(':adapters:tracing-inproc')
    testImplementation 'com.h2database:h2:2.2.224'
}
