#!/usr/bin/env python3
"""R9 nightly model-scale ladder (ROADMAP.md card R9; Track C C6; extends the reduced prelude done
in MASTER-ROADMAP.md Step 2a): deterministic synthetic model.json generator for the scale proof.
Used by scripts/proofs/run-scale-proof.ps1 for every rung (26/50/100/260/520 concepts) -- this
generator itself is unchanged by the full-ladder extension, since --concepts already accepted any
positive integer; only the driver script and its measurement phases grew.

Produces an N-concept schema-valid model, structurally modeled on the frozen
NPDevSamples/npdev-canary/Input/model.json fixture (same capability/binding/query/procedure/
panel/flow shape) so generation exercises the same pipeline shape at a larger concept count,
not a novel one. Deterministic by construction -- no randomness, no timestamps -- so the same
--concepts value always produces byte-identical output.

Only the FIRST synthesized concept gets a query/procedure/panel/flow (mirroring canary's own
"minimal, pipeline-complete" scope, R9's job is generate/build/boot SCALE, not DSL breadth --
dsl-conformance-max already covers that). The other N-1 concepts exist purely to scale
concept/table/entity count through the compiler and schema-realization path.

    python scripts/proofs/synthesize_scale_model.py --concepts 26 --out PATH/model.json
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

SCHEMA_REF = "model.schema.json"


def concept_name(index: int) -> str:
    return f"SyntheticConcept{index:04d}"


def build_concept(index: int) -> dict:
    name = concept_name(index)
    return {
        "name": name,
        "ui": {"label": f"Synthetic concept {index:04d}"},
        "fields": [
            {"name": "id", "type": "uuid", "id": True, "required": True},
            {"name": "label", "type": "string", "required": True, "ui": {"label": "Label"}},
            {"name": "sequence", "type": "integer", "required": True, "ui": {"label": "Sequence"}},
        ],
        "invariants": [
            {"name": f"{name}LabelRequired", "expr": "label != null && label != ''"}
        ],
    }


def build_model(concept_count: int) -> dict:
    if concept_count < 1:
        raise ValueError("concept_count must be >= 1")

    concepts = [build_concept(i) for i in range(1, concept_count + 1)]
    anchor = concept_name(1)

    return {
        "$schema": SCHEMA_REF,
        "namespace": "scaleproof.synthetic",
        "dslVersion": "1.0.0",
        "version": "1.0",
        "metadata": {
            "purpose": (
                f"R9 reduced scale ladder: deterministic {concept_count}-concept synthetic "
                "model, generated by scripts/proofs/synthesize_scale_model.py. Not a corpus "
                "fixture -- written outside the repo, never validated by the ai-knowledge gate."
            )
        },
        "concepts": concepts,
        "capabilities": [
            {"name": "persistence", "type": "PersistenceCapability", "operations": ["save", "findById"]}
        ],
        "bindings": [
            {"capability": "persistence", "adapter": "repository"},
            {"capability": "eventBus", "adapter": "inproc"},
        ],
        "queries": [
            {
                "name": f"All{anchor}",
                "concept": anchor,
                "where": "sequence >= 0",
                "orderBy": ["sequence"],
                "tracePolicy": "summary",
            }
        ],
        "procedures": [
            {
                "name": f"Save{anchor}Procedure",
                "description": f"Saves a {anchor} through the Concept Gateway and returns the governed record.",
                "parameters": [
                    {"name": "id", "type": "uuid", "required": True}
                ],
                "steps": [
                    {
                        "name": "save-through-gateway",
                        "type": "saveConcept",
                        "concept": anchor,
                        "id": "$id",
                        "data": {"input": "$input"},
                        "target": "saved",
                        "trace": True,
                        "audit": True,
                    },
                    {"name": "return-saved", "type": "return", "value": "$saved", "trace": True},
                ],
                "tracePolicy": "detailed",
            }
        ],
        "panels": [
            {
                "name": "ScaleProofPanel",
                "route": "/scale-proof/synthetic",
                "title": "Scale proof",
                "dataSources": [
                    {"name": "allRows", "query": f"All{anchor}"}
                ],
                "layout": {
                    "type": "table",
                    "fields": ["label", "sequence"],
                },
                "fieldBindings": [
                    {"field": "label", "source": "allRows.label"},
                    {"field": "sequence", "source": "allRows.sequence"},
                ],
                "explainability": {
                    "governedDataAccess": "ConceptGateway",
                    "ruleProfile": "always",
                },
            }
        ],
        "flows": [
            {
                "name": f"Create{anchor}",
                "input": {"concept": anchor, "mode": "create"},
                "steps": [
                    {
                        "name": "validate",
                        "type": "invariantCheck",
                        "scope": anchor,
                        "invariants": [f"{anchor}LabelRequired"],
                    },
                    {
                        "name": "save",
                        "type": "createConcept",
                        "scope": anchor,
                        "input": "$input",
                        "output": "$saved",
                    },
                    {"name": "return", "type": "return", "value": "$saved"},
                ],
            }
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--concepts", type=int, required=True, help="Number of concepts to synthesize")
    parser.add_argument("--out", type=Path, required=True, help="Output model.json path")
    args = parser.parse_args()

    model = build_model(args.concepts)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(model, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {args.out} ({args.concepts} concepts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
